name: Publish to Github Packages
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        registry-url: 'https://registry.npmjs.org'
        scope: '@mistakes0fficial'
    - name: Install dependencies
      run: npm install
    - name: Publish to Github Packages
      run: npm publish --access=public
      env:
        NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
